Repository CodePath-iOS-PlayDate/PlayDate, pull requests merged in 2021-11, with the labels that each got.

#21 Login VC finished
  PlayDate.xcodeproj/project.pbxproj
  PlayDate.xcworkspace/xcuserdata/dab.xcuserdatad/UserInterfaceState.xcuserstate
  PlayDate/Models/Pet.swift
  PlayDate/Models/User.swift
  PlayDate/Utilities/AuthManager.swift
  PlayDate/ViewControllers/FeedViewController.swift
  PlayDate/ViewControllers/LoginViewController.swift
  PlayDate/ViewControllers/MainLaunchViewController.swift
  PlayDate/ViewControllers/PetRegisterViewController.swift
  PlayDate/ViewControllers/UserRegisterViewController.swift
  PlayDate/ViewModels/Launch.swift
  PlayDate/ViewModels/Login.swift
  PlayDate/ViewModels/PetProfile.swift
  PlayDate/ViewModels/PetRegister.swift
  PlayDate/ViewModels/UserProfile.swift
  PlayDate/ViewModels/UserRegister.swift
  PlayDate/Views/Cells/MatchTableViewCell.swift
  PlayDate/Views/OnboardingTextField.swift
Labels: required

#24 Login vc new
  PlayDate.xcodeproj/project.pbxproj
  PlayDate.xcworkspace/xcuserdata/dab.xcuserdatad/UserInterfaceState.xcuserstate
  PlayDate/ViewControllers/LoginViewController.swift
  PlayDate/Views/OnboardingTextField.swift
Labels: required

#19 Main Launch VC Finished
  .gitignore
  PlayDate.xcodeproj/project.pbxproj
  PlayDate.xcworkspace/xcuserdata/dab.xcuserdatad/UserInterfaceState.xcuserstate
  PlayDate/AppDelegate.swift
  PlayDate/Assets.xcassets/LogoLarge.imageset/Contents.json
  PlayDate/Assets.xcassets/LogoLarge.imageset/ios-marketing.png
  PlayDate/Assets.xcassets/LogoMedium.imageset/Contents.json
  PlayDate/Assets.xcassets/LogoMedium.imageset/Logo256.png
  PlayDate/Assets.xcassets/LogoSmallMedium.imageset/Contents.json
  PlayDate/Assets.xcassets/LogoSmallMedium.imageset/icon-83.5@2x.png
  PlayDate/Utilities/Constants.swift
  PlayDate/ViewControllers/MainLaunchViewController.swift
Labels: required

#25 RegisterView logic and API setup. Logo and formatting pending.
  PlayDate/Base.lproj/LaunchScreen.storyboard
  PlayDate/Utilities/AuthManager.swift
  PlayDate/ViewControllers/UserRegisterViewController.swift
  Podfile
  Podfile.lock
  Pods/Manifest.lock
  Pods/Pods.xcodeproj/project.pbxproj
  Pods/Target Support Files/Firebase/Firebase.debug.xcconfig
  Pods/Target Support Files/Firebase/Firebase.release.xcconfig
  Pods/Target Support Files/Pods-PlayDate-PlayDateUITests/Pods-PlayDate-PlayDateUITests-acknowledgements.markdown
  Pods/Target Support Files/Pods-PlayDate-PlayDateUITests/Pods-PlayDate-PlayDateUITests-acknowledgements.plist
  Pods/Target Support Files/Pods-PlayDate-PlayDateUITests/Pods-PlayDate-PlayDateUITests-frameworks-Debug-input-files.xcfilelist
  Pods/Target Support Files/Pods-PlayDate-PlayDateUITests/Pods-PlayDate-PlayDateUITests-frameworks-Debug-output-files.xcfilelist
  Pods/Target Support Files/Pods-PlayDate-PlayDateUITests/Pods-PlayDate-PlayDateUITests-frameworks-Release-input-files.xcfilelist
  Pods/Target Support Files/Pods-PlayDate-PlayDateUITests/Pods-PlayDate-PlayDateUITests-frameworks-Release-output-files.xcfilelist
  Pods/Target Support Files/Pods-PlayDate-PlayDateUITests/Pods-PlayDate-PlayDateUITests-frameworks.sh
  Pods/Target Support Files/Pods-PlayDate-PlayDateUITests/Pods-PlayDate-PlayDateUITests.debug.xcconfig
  Pods/Target Support Files/Pods-PlayDate-PlayDateUITests/Pods-PlayDate-PlayDateUITests.release.xcconfig
  Pods/Target Support Files/Pods-PlayDate/Pods-PlayDate-acknowledgements.markdown
  Pods/Target Support Files/Pods-PlayDate/Pods-PlayDate-acknowledgements.plist
  Pods/Target Support Files/Pods-PlayDate/Pods-PlayDate-frameworks-Debug-input-files.xcfilelist
  Pods/Target Support Files/Pods-PlayDate/Pods-PlayDate-frameworks-Debug-output-files.xcfilelist
  Pods/Target Support Files/Pods-PlayDate/Pods-PlayDate-frameworks-Release-input-files.xcfilelist
  Pods/Target Support Files/Pods-PlayDate/Pods-PlayDate-frameworks-Release-output-files.xcfilelist
  Pods/Target Support Files/Pods-PlayDate/Pods-PlayDate-frameworks.sh
  Pods/Target Support Files/Pods-PlayDate/Pods-PlayDate.debug.xcconfig
  Pods/Target Support Files/Pods-PlayDate/Pods-PlayDate.release.xcconfig
  Pods/Target Support Files/Pods-PlayDateTests/Pods-PlayDateTests.debug.xcconfig
  Pods/Target Support Files/Pods-PlayDateTests/Pods-PlayDateTests.release.xcconfig
Labels: required

#32 Big commit - completed refining all views (MainLaunch, Login, Register)
  PlayDate.xcworkspace/xcuserdata/dab.xcuserdatad/UserInterfaceState.xcuserstate
  PlayDate/ViewControllers/LoginViewController.swift
  PlayDate/ViewControllers/MainLaunchViewController.swift
  PlayDate/ViewControllers/UserRegisterViewController.swift
  PlayDate/Views/OnboardingTextField.swift
Labels: enhancement

#35 User profile setup and header view
  PlayDate.xcodeproj/project.pbxproj
  PlayDate.xcworkspace/xcuserdata/dab.xcuserdatad/UserInterfaceState.xcuserstate
  PlayDate/Assets.xcassets/Colors/AccentColor.colorset/Contents.json
  PlayDate/Assets.xcassets/Colors/Contents.json
  PlayDate/Assets.xcassets/Colors/blueGreen.colorset/Contents.json
  PlayDate/Assets.xcassets/Colors/bluePurple.colorset/Contents.json
  PlayDate/Utilities/Constants.swift
  PlayDate/ViewControllers/HomeTabBarController.swift
  PlayDate/ViewControllers/ProfileViewController.swift
  PlayDate/ViewControllers/UserProfileViewController.swift
  PlayDate/Views/UserProfileCells/PetProfileViewCell.swift
  PlayDate/Views/UserProfileCells/UserProfileHeaderCell.swift
  PlayDate/Views/UserProfileCells/UserProfileViewCell.swift
Labels: required

#36 Keeps the User Logged In
  PlayDate.xcworkspace/xcuserdata/dab.xcuserdatad/UserInterfaceState.xcuserstate
  PlayDate/Utilities/Constants.swift
  PlayDate/ViewControllers/MainLaunchViewController.swift
  PlayDate/ViewControllers/UserProfileViewController.swift
  PlayDate/ViewControllers/UserRegisterViewController.swift
  PlayDate/Views/UserProfileCells/UserProfileHeaderCell.swift
Labels: required

#39 Sorry - bad merge is now fixed
  PlayDate/ViewControllers/UserProfileViewController.swift
  PlayDate/ViewControllers/UserRegisterViewController.swift
  PlayDate/Views/UserProfileCells/UserProfileHeaderCell.swift
Labels: bug

#40 Connected the home tab bar
  PlayDate/ViewControllers/MainLaunchViewController.swift
  PlayDate/ViewControllers/UserRegisterViewController.swift
Labels: required

#43 Organized the Tab controller files
  PlayDate.xcodeproj/project.pbxproj
  PlayDate.xcworkspace/xcuserdata/dab.xcuserdatad/UserInterfaceState.xcuserstate
  PlayDate/ViewControllers/Feed/FeedViewController.swift
  PlayDate/ViewControllers/Launch/LoginViewController.swift
  PlayDate/ViewControllers/Launch/MainLaunchViewController.swift
  PlayDate/ViewControllers/Launch/PetProfileSetupViewController.swift
  PlayDate/ViewControllers/Launch/UserRegisterViewController.swift
  PlayDate/ViewControllers/Matches/MatchListViewController.swift
  PlayDate/ViewControllers/Profile/UserProfileViewController.swift
Labels: enhancement

#45 User profile
  PlayDate.xcworkspace/xcuserdata/dab.xcuserdatad/UserInterfaceState.xcuserstate
  PlayDate.xcworkspace/xcuserdata/dab.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  PlayDate/Utilities/AuthManager.swift
  PlayDate/ViewControllers/HomeTabBarController.swift
  PlayDate/ViewControllers/Launch/LoginViewController.swift
  PlayDate/ViewControllers/Launch/UserRegisterViewController.swift
  PlayDate/ViewControllers/Profile/UserProfileViewController.swift
  PlayDate/Views/UserProfileCells/PetProfileViewCell.swift
  PlayDate/Views/UserProfileCells/UserProfileHeaderCell.swift
  PlayDate/Views/UserProfileCells/UserProfileViewCell.swift
Labels: required

#44 Camera / Photo Library Skeleton
  PlayDate/Info.plist
  PlayDate/ViewControllers/CameraViewController.swift
  PlayDate/ViewControllers/PhotoLibraryViewController.swift
Labels: required

#46 Pet models
  PlayDate/Models/Pet.swift
  PlayDate/Models/User.swift
  PlayDate/Utilities/AuthManager.swift
  Podfile
Labels: required
