Repository CodePath-iOS-PlayDate/PlayDate, pull requests merged in 2021-12, with the labels that each got.

#54 UserProfileSetupViewController added and connected
  PlayDate/Assets.xcassets/profilePicPlaceholder.imageset/Contents.json
  PlayDate/Assets.xcassets/profilePicPlaceholder.imageset/profilePicPlaceholder.png
  PlayDate/ViewControllers/Launch/UserProfileSetupViewController.swift
  PlayDate/ViewControllers/Launch/UserRegisterViewController.swift
Labels: required

#56 Swiping
  PlayDate.xcodeproj/project.pbxproj
  PlayDate.xcworkspace/xcuserdata/dab.xcuserdatad/UserInterfaceState.xcuserstate
  PlayDate/Utilities/AuthManager.swift
  PlayDate/Utilities/Constants.swift
  PlayDate/ViewControllers/Feed/FeedViewController.swift
  PlayDate/ViewModels/PetProfile.swift
  PlayDate/Views/FeedViews/CardContentView.swift
  PlayDate/Views/FeedViews/CardFooterView.swift
  PlayDate/Views/FeedViews/CardSwipeOverlay.swift
  PlayDate/Views/MatchCells/MatchTableViewCell.swift
Labels: required

#57 Added hotfix for bad merge on previous pull request
  .DS_Store
  PlayDate.xcodeproj/project.pbxproj
  PlayDate.xcworkspace/xcuserdata/dab.xcuserdatad/UserInterfaceState.xcuserstate
  PlayDate/.DS_Store
  PlayDate/Views/MatchCells/MatchHeaderTableViewCell.swift
  PlayDate/Views/MatchCells/MatchInfoTableViewCell.swift
  PlayDate/Views/MatchCells/MatchPicturesTableViewCell.swift
Labels: required

#58 User pet setup pictures
  PlayDate/Models/Pet.swift
  PlayDate/ViewControllers/Launch/PetProfileSetupViewController.swift
  PlayDate/ViewControllers/Launch/UserProfileSetupViewController.swift
Labels: required

#59 Hotfix onboarding
  PlayDate.xcworkspace/xcuserdata/dab.xcuserdatad/UserInterfaceState.xcuserstate
  PlayDate.xcworkspace/xcuserdata/dab.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  PlayDate/ViewControllers/Launch/PetProfileSetupViewController.swift
  PlayDate/ViewControllers/Launch/UserProfileSetupViewController.swift
  PlayDate/ViewControllers/Launch/UserRegisterViewController.swift
Labels: required

#60 ProfileTab Camera Button + LaunchScreen Logo
  PlayDate.xcodeproj/project.pbxproj
  PlayDate.xcodeproj/xcuserdata/gustavocornejov.xcuserdatad/xcschemes/xcschememanagement.plist
  PlayDate/Base.lproj/LaunchScreen.storyboard
  PlayDate/Views/UserProfileCells/UserProfileHeaderCell.swift
  Pods/Pods.xcodeproj/xcuserdata/gustavocornejov.xcuserdatad/xcschemes/xcschememanagement.plist
Labels: enhancement

#61 Finished connecting match list and match
  PlayDate.xcodeproj/project.pbxproj
  PlayDate.xcworkspace/xcuserdata/dab.xcuserdatad/UserInterfaceState.xcuserstate
  PlayDate/ViewControllers/Matches/MatchContactInfoViewController.swift
  PlayDate/ViewControllers/Matches/MatchListViewController.swift
Labels: required

#63 Added comments to indicate group in all files
  PlayDate.xcodeproj/project.pbxproj
  PlayDate.xcworkspace/xcuserdata/dab.xcuserdatad/UserInterfaceState.xcuserstate
  PlayDate/AppDelegate.swift
  PlayDate/Models/Pet.swift
  PlayDate/Models/User.swift
  PlayDate/Utilities/AuthManager.swift
  PlayDate/Utilities/Constants.swift
  PlayDate/ViewController.swift
  PlayDate/ViewControllers/Feed/FeedViewController.swift
  PlayDate/ViewControllers/HomeTabBarController.swift
  PlayDate/ViewControllers/Launch/LoginViewController.swift
  PlayDate/ViewControllers/Launch/MainLaunchViewController.swift
  PlayDate/ViewControllers/Launch/PetProfileSetupViewController.swift
  PlayDate/ViewControllers/Launch/UserProfileSetupViewController.swift
  PlayDate/ViewControllers/Launch/UserRegisterViewController.swift
  PlayDate/ViewControllers/Matches/MatchContactInfoViewController.swift
  PlayDate/ViewControllers/Matches/MatchListViewController.swift
  PlayDate/ViewControllers/Profile/UserProfileViewController.swift
  PlayDate/ViewModels/Launch.swift
  PlayDate/ViewModels/Login.swift
  PlayDate/ViewModels/PetProfile.swift
  PlayDate/ViewModels/PetRegister.swift
  PlayDate/ViewModels/UserProfile.swift
  PlayDate/ViewModels/UserRegister.swift
  PlayDate/Views/FeedViews/CardContentView.swift
  PlayDate/Views/FeedViews/CardFooterView.swift
  PlayDate/Views/FeedViews/CardSwipeOverlay.swift
  PlayDate/Views/MatchCells/MatchHeaderTableViewCell.swift
  PlayDate/Views/MatchCells/MatchInfoTableViewCell.swift
  PlayDate/Views/MatchCells/MatchPicturesTableViewCell.swift
  PlayDate/Views/MatchCells/MatchTableViewCell.swift
  PlayDate/Views/OnboardingTextField.swift
  PlayDate/Views/UserProfileCells/PetProfileViewCell.swift
  PlayDate/Views/UserProfileCells/UserProfileHeaderCell.swift
  PlayDate/Views/UserProfileCells/UserProfileViewCell.swift
Labels: documentation
